### ISSUE TITLE
Training using model_main_tf2.py no longer works in TF2.8+

### ISSUE THREAD

**Issue by aubricot** [aubricot/computer_vision_with_eol_images#9]
### Contact Details

eolglabs@gmail.com

### What happened?

When running the code to train the model using model_main_tf2.py, the model does not train. This used to work in Tensorflow 2.8, but after the backend upgrade to Tensorflow 2.9 this error started. After installing tf_slim, another error about tf.python.keras comes up. Even after downgrading to TF 2.8, the error is not fixed so I believe it is a dependency version causing the error.

```
#@title Train the model
# Note: You can change the number of epochs in code block above, then re-run to train longer
# Modified from https://github.com/RomRoc/objdet_train_tensorflow_colab/blob/master/objdet_custom_tf_colab.ipynb
matplotlib.use('Agg')
%cd $cwd

!python tf_models/models/research/object_detection/model_main_tf2.py \
    --alsologtostderr \
    --num_train_steps=$num_train_steps \
    --num_eval_steps=$num_eval_steps \
    --pipeline_config_path=$pipeline_config_path \
    --model_dir=$model_dir 
```

### How did you try to fix it?

I tried fixes [here](https://github.com/tensorflow/models/issues/10480), [here](https://github.com/tensorflow/models/issues/10479), [and here](https://github.com/tensorflow/models/issues/10479) but none of them worked. I also tried downgrading to TF 2.8, manually installing tf_slim, manuall editing resnet_v1.py from tf.python.keras.applications -> tf.keras.applications. Every time I try upgrading/downgrading the script that causes the problem, another traceback error is shown.

### Which type of our computer vision pipelines were you using?

Object detection for image cropping

### Which specific task from our computer vision pipelines were you using?

Chiroptera

### Filename

chiroptera_train_tf2_ssd_rcnn.ipynb

### Version

Version 2.8 and Version 2.9

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
/content/drive/MyDrive/train/tf2/nov22test
Traceback (most recent call last):
  File "tf_models/models/research/object_detection/model_main_tf2.py", line 35, in <module>
    from object_detection import model_lib_v2
  File "tf_models/models/research/object_detection/model_lib_v2.py", line 29, in <module>
    from object_detection import eval_util
  File "tf_models/models/research/object_detection/eval_util.py", line 29, in <module>
    import tf_slim as slim
ModuleNotFoundError: No module named 'tf_slim'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aubricot** [comment]
With the latest update to TF2.11, changes to which TF Object Detection Repo are cloned in the beginning, and how model config files are formatted within notebooks, this bug is now resolved.
